B040: Caught exception with call to add_note not used.

Did you forget to raise it?

See Also:
* Bugbear B040 - https://github.com/PyCQA/flake8-bugbear?tab=readme-ov-file
